routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.global');
});
// Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@user')->name('home/user');
Route::get('/home/admin', 'HomeController@adminHome')->name('home/admin')->middleware('level');
Route::resource('profil', 'ProfilController');
Route::resource('user', 'UsersController');

/*KETERANGAN CONTOH
Contoh Untuk Tampilan user : user.layout.master
Contoh Untuk Tampilan admin : admin.layout.master
*/
// Route::get('/master',function(){
//     return view('admin.layout.master');
// });

// Route::get('/test',function(){
//     return view('test');
// });

// Untuk komentar dari berita
Route::resource('berita', 'BeritaController');
Route::post('/berita/{beritum}/comment', 'BeritaCommentController@store')->name('berita.comment.store');

app/Profil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profil extends Model
{
    protected $table = "profile";
    protected $fillable = ["alamat", "umur", "user_id"];
}

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profil;
use App\User;

use Illuminate\Support\Facades\Auth;

class ProfilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $profile = Profil::where('user_id', Auth::user()->id)->first();
        return view('profil.index', compact('profile'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        profil::create([
            'umur' => $request->umur,
            'alamat' => $request->alamat,
            'user_id' => Auth::user()->id,
        ]);
        return redirect()->route('profil.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $profile_data = [
            'umur' => $request->umur,
            'alamat' => $request->alamat,
            'user_id' => Auth::user()->id,
        ];
        profil::whereId($id)->update($profile_data);
        
        return redirect()->route('profil.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/profil/index.blade.php
@extends('admin.layout.master')
@push('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
@endpush
@section('title')
    User id : {{ Auth::user()->name }}
@endsection
@section('content')
{{-- User id : {{ Auth::user()->name }} --}}

@if ($profile != null)
<div class="container">
    <form action="">
        <div class="form-group">
            <label for="name">Nama Lengkap : {{Auth::user()->name}}</label><br>
            <label for="">Email : {{Auth::user()->email}}</label>
        </div>
    </form>
    <hr>
    <form method="POST" action="{{ route('profil.update', [$profile->id]) }}">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="umur">Umur</label>
            <input type="number" id="umur" name="umur" value="{{ $profile->umur }}" class="form-control" placeholder="Umur" autofocus>
        </div>
        <div class="fomr-group">
            <label for="alamat">Alamat</label>
            <textarea name="alamat" value="" id="alamat" cols="30" rows="10" class="form-control">{{ $profile->alamat }}</textarea>
        </div>
        <div class="form-group">
            <div class="row mt-3">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-primary btn-block">Edit</button>
                </div>
                <div class="col-md-6">
                    <button type="reset" class="btn btn-warning btn-block">Reset</button>
                </div>
            </div>
        </div>    
    </form>
</div>
@else
    {{-- insert profil --}}
<div class="container">
    <form action="{{ route('profil.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="umur">Umur</label>
            <input type="number" id="umur" name="umur" class="form-control" placeholder="Umur" autofocus>
        </div>
        <div class="fomr-group">
            <label for="alamat">Alamat</label>
            <textarea name="alamat" id="alamat" cols="30" rows="10" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <div class="row mt-3">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-primary btn-block">Simpan</button>
                </div>
                <div class="col-md-6">
                    <button type="reset" class="btn btn-warning btn-block">Reset</button>
                </div>
            </div>
        </div>    
    </form>
</div>
@endif



{{-- <table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
        <th>Umur</th>
        <th>Alamat</th>
        <th>Platform(s)</th>
        <th>Engine version</th>
        <th>CSS grade</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td>Trident</td>
        <td>Internet
            Explorer 4.0
        </td>
        <td>Win 95+</td>
        <td> 4</td>
        <td>X</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>Rendering engine</th>
            <th>Browser</th>
            <th>Platform(s)</th>
            <th>Engine version</th>
            <th>CSS grade</th>
        </tr>
    </tfoot>
    </table>
 --}}
@endsection
@push('js')
<script src="{{ asset('asset/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('asset/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
@endpush