routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.global');
});
// Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@user')->name('home/user');
Route::get('/home/admin', 'HomeController@adminHome')->name('home/admin')->middleware('level');
Route::resource('profil', 'ProfilController');
Route::resource('user', 'UsersController');

/*KETERANGAN CONTOH
Contoh Untuk Tampilan user : user.layout.master
Contoh Untuk Tampilan admin : admin.layout.master
*/
// Route::get('/master',function(){
//     return view('admin.layout.master');
// });

// Route::get('/test',function(){
//     return view('test');
// });

// Untuk komentar dari berita
Route::resource('berita', 'BeritaController');
Route::post('/berita/{beritum}/comment', 'BeritaCommentController@store')->name('berita.comment.store');

app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $table = "berita";
    protected $fillable = ["judul", "konten", "penulis", "user_id"];
    
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/BeritaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Berita;
use DB;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $berita = DB::table('berita')->get();
        return view('admin.berita.index', compact('berita'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $admins = User::all();
        return view('admin.berita.create', compact('admins'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'judul' => 'required',
            'konten' => 'required',
            'penulis' => 'required',
            'user_id' => 'required',
        ]);

        Berita::create([
            'judul' => $request->judul,
            'konten' => $request->konten,
            'penulis' => $request->penulis,
            'user_id' => $request->user_id
        ]);
        
        return redirect('/berita');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $berita = DB::table('berita')->where('id', $id)->first();
        return view('admin.berita.show', compact('berita'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::all();
        $berita = Berita::findorfail($id);
        return view('admin.berita.edit', compact('berita', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request,[
        //     'judul' => 'required',
        //     'konten' => 'required',
        //     'penulis' => 'required',
        //     'user_id' => 'required',
        // ]);
        $berita_data =  [
            'judul' => $request->judul,
            'konten' => $request->konten,
            'penulis' => $request->penulis,
            'user_id' => $request->user_id
        ];
        berita::whereId($id)->update($berita_data);
        return redirect('/berita');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $berita = Berita::findorfail($id);
        $berita->delete();
        return redirect('/berita');
    }
}

resources/views/admin/berita/create.blade.php
@extends('admin.layout.master')

  @section('title')
    Tambah Berita
  @endsection


  @section('content')
    <div>
        <form method="POST" action="{{ route('berita.store') }}">
            @csrf
            {{-- @method('POST') --}}
            <div class="form-group">
                <label for="title">Judul</label>
                <input type="text" class="form-control" name="judul" id="judul" placeholder="Masukkan Judul Berita">
                @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">Konten</label>
                <input type="text" class="form-control" name="konten" id="konten" placeholder="Masukkan Konten">
                @error('umur')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">Penulis</label>
                <input type="text" class="form-control" name="penulis" id="penulis" placeholder="Masukkan Nama Penulis">
                @error('penulis')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">Email</label>
                <select name="user_id" id="email"  class="form-control">
                    <option value="">-</option>
                    @foreach ($admins as $value)
                        <option value="{{$value->id}}">{{$value->email}}</option>
                    @endforeach
                </select>
            @error('user_id')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror   
            </div>
            <button type="submit" class="btn btn-primary">Tambah</button>
        </form>
    </div>

  

  @endsection

  

resources/views/admin/berita/edit.blade.php
@extends('admin.layout.master')
@push('css')
    <style>
    
/* For other boilerplate styles, see: /docs/general-configuration-guide/boilerplate-content-css/ */
/*
* For rendering images inserted using the image plugin.
* Includes image captions using the HTML5 figure element.
*/

figure.image {
  display: inline-block;
  border: 1px solid gray;
  margin: 0 2px 0 1px;
  background: #f5f2f0;
}

figure.align-left {
  float: left;
}

figure.align-right {
  float: right;
}

figure.image img {
  margin: 8px 8px 0 8px;
}

figure.image figcaption {
  margin: 6px 8px 6px 8px;
  text-align: center;
}


/*
 Alignment using classes rather than inline styles
 check out the "formats" option
*/

img.align-left {
  float: left;
}

img.align-right {
  float: right;
}

/* Basic styles for Table of Contents plugin (toc) */
.mce-toc {
  border: 1px solid gray;
}

.mce-toc h2 {
  margin: 4px;
}

.mce-toc li {
  list-style-type: none;
}

    </style>
@endpush

  @section('title')

    Edit Berita id ke {{$berita->id}}

  @endsection

  @section('content')
    <div>
        <form action="{{ route('berita.update', [$berita->id]) }} " method="POST">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="title">Judul</label>
                <input type="text" class="form-control" value="{{$berita->judul}}" name="judul" id="judul" placeholder="Masukkan Judul Berita">
                @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">Konten</label>
                
                <textarea id="full-featured-non-premium" name="konten" id="konten">{{$berita->konten}}</textarea>

                {{-- <input type="text" class="form-control" value="" name="konten" id="konten" placeholder="Masukkan Konten"> --}}
                @error('konten')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
                <script src="https://cdn.tiny.cloud/1/45f3xae6clgfqd2zqnwokgzzxs97kqlmfbhqf4uajdmune54/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
                
            </div>
            <div class="form-group">
                <label for="body">Penulis</label>
                <input type="text" class="form-control" value="{{$berita->penulis}}" name="penulis" id="penulis" placeholder="Masukkan Nama Penulis">
                @error('penulis')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="body">Email</label>
                <select name="user_id" id="email"  class="form-control">
                    <option value="">-</option>
                    @foreach ($users as $value)
                        @if ($value->id == $berita->id)
                        <option value="{{$value->id}}" selected>{{$value->email}}</option>                            
                        @else
                        <option value="{{$value->id}}">{{$value->email}}</option> 
                        @endif
                    @endforeach
                </select>
                @error('user_id')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror   
            </div>
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </div>
  @endsection
  @push('js')
      <script>

var useDarkMode = window.matchMedia('(prefers-color-scheme: light)').matches;

tinymce.init({
  selector: 'textarea#full-featured-non-premium',
  plugins: 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
  imagetools_cors_hosts: ['picsum.photos'],
  menubar: 'file edit view insert format tools table help',
  toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl',
  toolbar_sticky: true,
  autosave_ask_before_unload: true,
  autosave_interval: '30s',
  autosave_prefix: '{path}{query}-{id}-',
  autosave_restore_when_empty: false,
  autosave_retention: '2m',
  image_advtab: true,
  link_list: [
    { title: 'My page 1', value: 'https://www.tiny.cloud' },
    { title: 'My page 2', value: 'http://www.moxiecode.com' }
  ],
  image_list: [
    { title: 'My page 1', value: 'https://www.tiny.cloud' },
    { title: 'My page 2', value: 'http://www.moxiecode.com' }
  ],
  image_class_list: [
    { title: 'None', value: '' },
    { title: 'Some class', value: 'class-name' }
  ],
  importcss_append: true,
  file_picker_callback: function (callback, value, meta) {
    /* Provide file and text for the link dialog */
    if (meta.filetype === 'file') {
      callback('https://www.google.com/logos/google.jpg', { text: 'My text' });
    }

    /* Provide image and alt text for the image dialog */
    if (meta.filetype === 'image') {
      callback('https://www.google.com/logos/google.jpg', { alt: 'My alt text' });
    }

    /* Provide alternative source and posted for the media dialog */
    if (meta.filetype === 'media') {
      callback('movie.mp4', { source2: 'alt.ogg', poster: 'https://www.google.com/logos/google.jpg' });
    }
  },
  templates: [
        { title: 'New Table', description: 'creates a new table', content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>' },
    { title: 'Starting my story', description: 'A cure for writers block', content: 'Once upon a time...' },
    { title: 'New list with dates', description: 'New List with dates', content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>' }
  ],
  template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
  template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
  height: 600,
  image_caption: true,
  quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
  noneditable_noneditable_class: 'mceNonEditable',
  toolbar_mode: 'sliding',
  contextmenu: 'link image imagetools table',
  skin: useDarkMode ? 'oxide-dark' : 'oxide',
  content_css: useDarkMode ? 'dark' : 'default',
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
 });



      </script>
  @endpush

resources/views/admin/berita/index.blade.php
@extends('admin.layout.master')
@push('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
@endpush

  @section('title')
    Daftar Berita
  @endsection


  @section('content')
    <a href="{{ route('berita.create') }}" class="btn btn-primary my-2">Tambah</a>

    <table class="table">
        <thead class="thead-light">
            <tr>
            <th scope="col">#</th>
            <th scope="col">Judul</th>
            {{-- <th scope="col">Konten</th> --}}
            <th scope="col">Penulis</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($berita as $key=>$value)
                <tr>
                    <td>{{$key + 1}}</th>
                    <td>{{$value->judul}}</td>
                    {{-- <td>{{$value->konten}}</td> --}}
                    <td>{{$value->penulis}}</td>
                    <td>
                        <form action="/berita/{{$value->id}}" method="POST">
                            <a href="/berita/{{$value->id}}" class="btn btn-info">Show</a>
                            <a href="{{ route('berita.edit', [$value->id]) }}" class="btn btn-primary">Edit</a>
                            @csrf
                            @method('DELETE')
                            <input type="submit" class="btn btn-danger my-1" value="Delete">
                        </form>
                    </td>
                </tr>
            @empty
                <tr colspan="3">
                    <td>No data</td>
                </tr>  
            @endforelse              
        </tbody>
    </table>
  @endsection
  @push('js')
    {{-- <script src="http://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script> --}}
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
    <script>
    $(function () {
        $("#example1").DataTable();
    });
    </script>
@endpush

resources/views/admin/berita/show.blade.php
@extends('admin.layout.master')

  @section('title')
    Show berita id: {{$berita->id}}
  @endsection


  @section('content')
  {{-- @include('comment.php') --}}
  <p>{{$berita->judul}}</p>
  <p>{{$berita->konten}}</p>
  <p>{{$berita->penulis}}</p>

  <div class="panel panel-default">
      <div class="panel-heading">Tambahkan Komentar</div>
      @foreach ($berita->comment()->get() as $comment)
        <div class="panel-body">
            <h4>{{$comment->users->name}} - {{$comment->created_at->diffForHumans()}}</h4>

            <p>{{$comment->komentar}}</p>
        </div>
          
      @endforeach
      <div class="panel-body">
          <form action="{{route('berita.comment.store', $berita)}}" method="post" class="form-horizontal">
            {{csrf_field()}}
                <textarea name="komentar" id="" cols="30" rows="5" class="form-control" placeholder="Berikan Komentar"></textarea>
                           
                <input type="submit" value="Komentar" class ="btn btn-primary">
              
          </form>
        </div>
    </div> 

  @endsection

  